# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CI

on:
  push:
    branches: [ "*", "*/*" ]
  pull_request:
    branches: [ "*", "*/*"  ]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Grant write access to pull requests
      contents: read        # Grant read access to repository contents
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Label if it doesn't exist
        run: |
          if ! gh label list | grep -q 'automated-pr'; then
            gh label create 'automated-pr' --color 'f29559'
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        run: |
          gh pr create \
            --base "${{ github.event.inputs.base_branch || 'main' }}" \
            --head "${{ github.event.inputs.branch_to_merge }}" \
            --title "Merge ${{ github.event.inputs.branch_to_merge }} into ${{ github.event.inputs.base_branch || 'main' }}" \
            --body "Created by Github action" \
            --label "automated-pr"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Build Python libs
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: libs
      shell: bash
      run: |
        make setup-project

    - name: Finalize Release files
      uses: AButler/upload-release-assets@v3.0
      with:
        files: "*.exe"
        repo-token: ${{ secrets.GITHUB_TOKEN }}

